RockPaperScissors_SimpleV/Models/GameChoiceModel.cs
namespace RockPaperScissors_SimpleV.Models
{
    public class GameChoiceModel
    {
        public int StatusCode { get; set; } 
        public string? Body { get; set; }
        public string? WhosChoice { get; set; }
    }
}

RockPaperScissors_SimpleV/Models/GameResultModel.cs
namespace RockPaperScissors_SimpleV.Models
{
    public class GameResultModel
    {
        public string WhosWinner { get; set; } 
        public string PlayerChoice{ get; set; }
        public string GameChoice { get; set; }
        public string WhosChoice { get; set; }
    }
}

RockPaperScissors_SimpleV/Pages/Error.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Diagnostics;

namespace RockPaperScissors_SimpleV.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    [IgnoreAntiforgeryToken]
    public class ErrorModel : PageModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

RockPaperScissors_SimpleV/Pages/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc.RazorPages;
using RockPaperScissors_SimpleV.Services;
using RockPaperScissors_SimpleV.CurbServices;

namespace RockPaperScissors_SimpleV.Pages
{
    public class IndexModel : PageModel
    {
        IConfiguration _configuration;
        IGameResults _gameResults;
        IGameChoice _gameChoice;
        public string Message { get; set; }

        public IndexModel(IConfiguration configuration, IGameResults gameResults, IGameChoice gameChoice)
        {
            _configuration = configuration;
            _gameResults = gameResults;
            _gameChoice = gameChoice;
        }
        
        public async Task OnPostRockAsync()
        {
            var botChoice = await _gameChoice.GameIsChoosing(_configuration);
            var message = _gameResults.ShowGameResult("rock", botChoice);

            Message = $"{ message} ";
        }

        public async Task OnPostPaperAsync()
        {
            var botChoice = await _gameChoice.GameIsChoosing(_configuration);
            var message = _gameResults.ShowGameResult("paper", botChoice);

            Message = $"{ message}";
        }

        public async Task OnPostScissorsAsync()
        {
            var botChoice = await _gameChoice.GameIsChoosing(_configuration);
            var message = _gameResults.ShowGameResult("scissors", botChoice);

            Message = $"{ message}";
        }
    }
}

RockPaperScissors_SimpleV/Pages/Privacy.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace RockPaperScissors_SimpleV.Pages
{
    public class PrivacyModel : PageModel
    {
        private readonly ILogger<PrivacyModel> _logger;

        public PrivacyModel(ILogger<PrivacyModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
        }
    }
}

RockPaperScissors_SimpleV/Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Home page";
}

<div class="text-center">
    <h1 class="display-4" style="color: #800080">Rock Papper Scissors</h1>
<div style="text-align: center;"><p style="color: gray" >Rock Paper Scissors is a zero sum game that is usually played by two people using their hands and no tools. The idea is to make shapes with an outstretched hand where each shape will have a certain degree of power and will lead to an outcome.</p></div>

<form method="post">
    <h2>Rock Paper or Scissors?</h2>
    <a href="#main"><input type="image" src="~/Paper.png" alt="Paper" width="63" height="139" value="Paper" asp-page-handler="Paper"  /></a>  
    <a href="#main"><input type="image" src="~/Rock.png" alt="Rock" width="63" height="139" value="Rock" asp-page-handler="Rock"  /></a>    
    <a href="#main"><input type="image" src="~/Scissors.png" alt="Scissors" width="63" height="139" value="Scissors" asp-page-handler="Scissors"/></a>
</form>

<h3>@Model.Message</h3>

RockPaperScissors_SimpleV/Pages/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - RockPaperScissors_SimpleV</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/RockPaperScissors_SimpleV.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-page="/Index">RockPaperScissors_SimpleV</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - RockPaperScissors_SimpleV - <a asp-area="" asp-page="/Privacy">Privacy</a>
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>